server:
  port: 8080

spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://rebook-eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

app:
  jwt:
    secret: ${APP_JWT_SECRET:change-me-in-env}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: DEBUG
