apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: rebook
spec:
  selector:
    app: eureka-server
  ports:
    - port: 8761
      targetPort: 8761
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: rebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: srujanreddynadipi/rebook-eureka-server:latest
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: rebook
spec:
  selector:
    app: api-gateway
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: rebook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: srujanreddynadipi/rebook-api-gateway:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: APP_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: APP_JWT_SECRET
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: rebook
spec:
  selector:
    app: auth-service
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: rebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: srujanreddynadipi/rebook-auth-service:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: APP_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: APP_JWT_SECRET
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: book-service
  namespace: rebook
spec:
  selector:
    app: book-service
  ports:
    - port: 8082
      targetPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
  namespace: rebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
        - name: book-service
          image: srujanreddynadipi/rebook-book-service:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          ports:
            - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: request-service
  namespace: rebook
spec:
  selector:
    app: request-service
  ports:
    - port: 8083
      targetPort: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-service
  namespace: rebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: request-service
  template:
    metadata:
      labels:
        app: request-service
    spec:
      containers:
        - name: request-service
          image: srujanreddynadipi/rebook-request-service:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          ports:
            - containerPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: rebook
spec:
  selector:
    app: chat-service
  ports:
    - port: 8084
      targetPort: 8084
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: rebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: srujanreddynadipi/rebook-chat-service:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: APP_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: APP_JWT_SECRET
          ports:
            - containerPort: 8084

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: rebook
spec:
  selector:
    app: notification-service
  ports:
    - port: 8085
      targetPort: 8085
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: rebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: srujanreddynadipi/rebook-notification-service:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          ports:
            - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: rebook
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: rebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: srujanreddynadipi/rebook-frontend:latest
          ports:
            - containerPort: 80
